### PR TITLE
MAINT: Bump to 7.4.1 and add larsoner

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] ~~Bumped the build number (if the version is unchanged)~~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adds me (@larsoner) as a maintainer and bumps to 7.4.1. EDIT: And adds automerge

Closes #29
Closes #28

### CODE REVIEW

**Comment by larsoner** [comment]
@conda-forge-admin, please rerender

**Comment by larsoner** [comment]
Added automerge, bumped, added myself as maintainer, and it's green. Feel free to review/merge @grlee77 !

**Comment by larsoner** [comment]
@conda-forge-admin please rerender

**Review by grlee77 — APPROVED** [review]
Thanks, Eric!

**Pull request merged**
